### ISSUE TITLE
References to your stanford website are broken

### ISSUE THREAD

**Issue by gabefair** [sleepinyourhat/vector-entailment#2]
I assume the links no longer work because you have graduated. Congrats. For anyone who has arrived here via a footnote from one of Dr. Bowman's papers, I found an archive here: https://web.archive.org/web/20150728093601/http://web.stanford.edu/~sbowman/

**Comment by sleepinyourhat** [comment]
Thanks! I fixed the overall repo URL to point to my current NYU site and added links to the relevant papers. Did you see any other dead links?

**Comment by gabefair** [comment]
Nope, thats it. Thank you
